"""./generate_migrations

Revision ID: 10fff1c96965
Revises: 6da73feb70b3
Create Date: 2021-10-18 21:48:01.167457

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "10fff1c96965"
down_revision = "6da73feb70b3"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("booking", sa.Column("name", sa.String(), nullable=True))
    op.create_unique_constraint(None, "booking", ["id"])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "booking", type_="unique")
    op.drop_column("booking", "name")
    # ### end Alembic commands ###
