"""./generate_migrations

Revision ID: 6da73feb70b3
Revises: 
Create Date: 2021-10-18 21:03:25.073819

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6da73feb70b3"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "booking",
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("date", sa.Date(), nullable=True),
        sa.Column("deposit", sa.Float(), nullable=True),
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("number_of_heads", sa.Integer(), nullable=True),
        sa.Column("has_paid", sa.Boolean(), nullable=True),
        sa.Column("time", sa.Time(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("booking")
    # ### end Alembic commands ###
